"""empty message

Revision ID: 77a1d92e96a6
Revises: 
Create Date: 2025-01-24 19:21:57.804258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a1d92e96a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_personaje', sa.String(length=50), nullable=False),
    sa.Column('color_de_ojos', sa.String(length=100), nullable=False),
    sa.Column('color_de_pelo', sa.String(length=20), nullable=False),
    sa.Column('altura_de', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_planeta', sa.String(length=50), nullable=False),
    sa.Column('poblacion', sa.String(length=20), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=20), nullable=False),
    sa.Column('suscripcion', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuarios_id', sa.Integer(), nullable=False),
    sa.Column('planetas_id', sa.Integer(), nullable=False),
    sa.Column('personajes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personajes_id'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['planetas_id'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['usuarios_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    op.drop_table('usuarios')
    op.drop_table('planetas')
    op.drop_table('personajes')
    # ### end Alembic commands ###
