"""empty message

Revision ID: bc3fa7497c20
Revises: 77a1d92e96a6
Create Date: 2025-01-24 19:26:18.730860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3fa7497c20'
down_revision = '77a1d92e96a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_constraint('favoritos_usuarios_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favoritos_personajes_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favoritos_planetas_id_fkey', type_='foreignkey')
        batch_op.drop_column('personajes_id')
        batch_op.drop_column('usuarios_id')
        batch_op.drop_column('planetas_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planetas_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('usuarios_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('personajes_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('favoritos_planetas_id_fkey', 'planetas', ['planetas_id'], ['id'])
        batch_op.create_foreign_key('favoritos_personajes_id_fkey', 'personajes', ['personajes_id'], ['id'])
        batch_op.create_foreign_key('favoritos_usuarios_id_fkey', 'usuarios', ['usuarios_id'], ['id'])

    # ### end Alembic commands ###
